#pragma once
#include "ecs/Entity.h"
#include "ecs/Component.h"
#include "ecs/Registry.h"
#include "ecs/System.h"
#include "ecs/NavComponent.h"
#include "ecs/PathfindingSystem.h"
#include "ecs/BehaviorComponent.h"
#include "ecs/BehaviorSystem.h"
