name: build-and-test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [debug, release]

    steps:
      - uses: actions/checkout@v4

      - name: Install CMake & Ninja
        uses: lukka/get-cmake@v3

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: '**/vcpkg.json'
          runVcpkgInstall: true

      - name: Configure
        run: cmake --preset ${{ matrix.build_type }}

      - name: Build
        run: cmake --build --preset ${{ matrix.build_type }}

      - name: Test
        run: ctest --preset default --output-on-failure

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: promethean-${{ matrix.os }}-${{ matrix.build_type }}
          path: build/${{ matrix.build_type }}/promethean${{ matrix.os == 'windows-latest' && '.exe' || '' }}
