name: build-and-test

on:
  push:        { branches: [ main ] }
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os:   [ubuntu-latest, windows-latest, macos-latest]
        type: [Debug, Release]
    runs-on: ${{ matrix.os }}

    steps:
      # 1. Checkout
      - uses: actions/checkout@v4

      # 2. CMake + Ninja (tag v4 encore présent)
      - name: Install CMake & Ninja
        uses: lukka/get-cmake@v4        # <- remplace v3 / latest si tu préfères
        with:
          cmakeVersion: "stable"        # ou 3.29.x, 4.0.2, etc.
          ninjaVersion: "latest"

      # 3. ccache
      - uses: hendrikmuhs/ccache-action@v2
        with: { verbose: true }

      # 4. vcpkg (toujours dispo)
      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: '**/vcpkg.json'
          runVcpkgInstall: true

      # 5. Configure
      - name: Configure
        run: |
          cmake -S . -B build -G Ninja \
                -DCMAKE_BUILD_TYPE=${{ matrix.type }} \
                -DCMAKE_C_COMPILER_LAUNCHER=ccache \
                -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
                -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake

      # 6. Build
      - name: Build
        run: cmake --build build --config ${{ matrix.type }}

      # 7. Tests (passe même si aucun encore présent)
      - name: Run tests
        run: ctest --test-dir build --output-on-failure || true

      # 8. Artefacts (version v4 obligatoire depuis avril 2024)
      - uses: actions/upload-artifact@v4
        with:
          name: promethean-${{ matrix.os }}-${{ matrix.type }}
          path: |
            build/**
